# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_recordingSuite0():
    client = WindmillTestClient(__name__)

    client.click(link=u'Resources')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'Energy Hub', timeout=u'8000')
    client.click(link=u'Energy Hub')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'Billboard', timeout=u'8000')
    client.click(link=u'Billboard')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'About', timeout=u'8000')
    client.click(link=u'About')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertText(xpath=u"//div[@id='content']/div[2]/div/h3", validator=u'About the Kukui Cup Competition')