# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_check_tabs():
  client = WindmillTestClient(__name__)

  client.open(url=u'http://localhost:8000/')
  client.click(link=u'Resources')
  client.waits.forPageLoad(timeout=u'20000')
  client.waits.forElement(link=u'Energy Hub', timeout=u'8000')
  client.click(link=u'Energy Hub')
  client.waits.forPageLoad(timeout=u'20000')
  client.waits.forElement(link=u'Billboard', timeout=u'8000')
  client.click(link=u'Billboard')
  client.waits.forPageLoad(timeout=u'20000')
  client.waits.forElement(link=u'About', timeout=u'8000')
  client.click(link=u'About')
  client.waits.forPageLoad(timeout=u'20000')
  client.asserts.assertText(xpath=u"//div[@id='content']/div[2]/div/h3", validator=u'About the Kukui Cup Competition')
    
def test_admin_open():
  client = WindmillTestClient(__name__)

  client.open(url=u'http://localhost:8000/account/login')
  client.waits.forPageLoad(timeout=u'8000')
  client.type(text=u'admin', id=u'id_username')
  client.type(text=u'changeme', id=u'id_password')
  client.click(value=u'Log in \xbb')
  client.waits.forPageLoad(timeout=u'20000')
  client.waits.forElement(xpath=u"//div[@id='home_tab']/a[3]/span", timeout=u'8000')
  client.click(xpath=u"//div[@id='home_tab']/a[3]/span")
  client.waits.forPageLoad(timeout=u'20000')
  client.waits.forElement(link=u'Log out', timeout=u'8000')
  client.click(link=u'Log out')
  client.waits.forPageLoad(timeout=u'20000')
  client.asserts.assertText(xpath=u"//div[@id='content']/h1", validator=u'Logged out')

