from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^$', 'pages.view_help.views.index', name='help_index'),
	url(r'^defineKukuiCup/$', 'pages.view_help.views.defineKukuiCup', name='help_defineKukuiCup'),
	url(r'^termsConditions/$', 'pages.view_help.views.termsConditions', name='help_termsConditions'),
	url(r'^figureBaseline/$', 'pages.view_help.views.figureBaseline', name='help_figureBaseline'),
	url(r'^plugLoad/$', 'pages.view_help.views.plugLoad', name='help_plugLoad'),
	url(r'^collaborate/$', 'pages.view_help.views.collaborate', name='help_collaborate'),
	url(r'^contact/$', 'pages.view_help.views.contact', name='help_contact'),
	url(r'^timeline/$', 'pages.view_help.views.timeline', name='help_timeline'),
	url(r'^competitions/$', 'pages.view_help.views.competitions', name='help_competitions'),
	url(r'^conservation/$', 'pages.view_help.views.conservation', name='help_conservation'),
	url(r'^kukuinutpoints/$', 'pages.view_help.views.kukuinutpoints', name='help_kukuinutpoints'),
	url(r'^activities/$', 'pages.view_help.views.activities', name='help_activities'),
	url(r'^committments/$', 'pages.view_help.views.committments', name='help_committments'),
	url(r'^conservationgoal/$', 'pages.view_help.views.conservationgoal', name='help_conservationgoal'),
	url(r'^awardprizes/$', 'pages.view_help.views.awardprizes', name='help_awardprizes'),
	url(r'^eventoftie/$', 'pages.view_help.views.eventoftie', name='help_eventoftie'),
	url(r'^raffle/$', 'pages.view_help.views.raffle', name='help_raffle'),
)
